--- 
title: "STAT 362 R for Data Science"
author: "Brian Ling"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Notes for STAT 362"
---


# Syllabus {-}

Course Description: Introduction to R, data creation and manipulation, data import and export, scripts and functions, control flow, debugging and profiling, data visualization, statistical inference, Monte Carlo methods, decision trees, support vector machines, neural network, numerical methods.



**Teacher assistant:** TBD

**Office Hours:**

**Intended Student Learning Outcomes**:


1. Understand the fundamental concepts in R
1. Be able to import and tidy data for further analysis.
1. 

**Prerequisite**



**Textbooks/Readings**

1. R Markdown: The Definitive Guide
1. R for Data Science, by Garrett Grolemund and Hadley Wickham

**Course Outline**

1. Installing R, Rstudio and packages
1. Basic data types and operations
1. Data structures: vector, matrix, array, list, dara frame
1. Data input and output
1. Scripts and functinos
1. Control flow
1. Debugging and profiling
1. Data visualization with ggplot2
1. Data manipulation with tidyverse
1. Statistical inference in R: one/two-sample test of mean and proportion; correlation test; non-parametric test; regression analysis
1. Introduction to Monte Carlo methods
1. Decision trees, support vector machines, neural network
1. Introduction to numericacl methods: gradient descent, Newton Raphson algorithm


**Grading Scheme**
30% assignments, 30% Midterm, 40% Final Project 

***Assignments***
6 Assignments 
Late submission: receive 80% of the points (within one day), receive 0 (after one day)

Solution will be posted after one day of the due date
One assignment with the lowest score will be dropped


***Final Project***
Form a group of 5-6 students.
25% Final Report
15% Final Presentation
